title: "CTF Writeups"
description: "Writeups and notes from my CTF journey"
theme: jekyll-theme-hacker

# These two lines make links work under /CTF-Writeups/
url: "https://ryanethier.github.io"
baseurl: "/CTF-Writeups"
